### ISSUE TITLE
limbs - argument min.rate() can be dropped

### ISSUE THREAD

**Issue by DanluGuo** [conradwasko/hydroEvents#22]
The function defaults to separate rising/falling limbs by 
rising: c(Str : max(when diff(Q) > min.rate[1])) 
falling: c(max(when diff(Q) > min.rate[1])+1 : End) 
This is essentially same as separating by the peak. 

I think this is sufficient for now and maybe no need for a flexible approach - if so the function needs to be simplified.

**Comment by conradwasko** [comment]
The argument has been dropped
